// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmbcveyrjuqjdwkbmecl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtYmN2ZXlyanVxamR3a2JtZWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDUwNDUsImV4cCI6MjA2ODM4MTA0NX0.qfHcPlEYe2kftvkjrAH-bzUtYpy4bgkjQcobxTRAo6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);