// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frxffozynwulkhiidjce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeGZmb3p5bnd1bGtoaWlkamNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODE5NzcsImV4cCI6MjA2NDI1Nzk3N30.coHxrIo98S6upmszJB1Bh9Yz5zeBCvbcVcJNQYvD6Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);